### ISSUE TITLE
Error " URL contained a potentially malicious String "%2F"" deploy_flow_version

### ISSUE THREAD

**Issue by saggarsunil** [Chaffelson/nipyapi#135]
* Nipyapi version: 0.13.2
* NiFi version: 1.9.2
* NiFi-Registry version: 0.4.0
* Python version: 3.4
* Operating System: Mac

### Description

Http error while running nipyapi.versioning.deploy_flow_version API

### What I Did
```
>>> nipyapi.versioning.deploy_flow_version(rootPg, location, bucketID, workflowID, registryID, ver)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nipyapi/versioning.py", line 792, in deploy_flow_version
    version=target_flow.version
  File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/apis/process_groups_api.py", line 858, in create_process_group
    (data) = self.create_process_group_with_http_info(id, body, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/apis/process_groups_api.py", line 945, in create_process_group_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/api_client.py", line 326, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/api_client.py", line 153, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/api_client.py", line 371, in request
    body=body)
  File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/rest.py", line 268, in POST
    body=body)
  File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/rest.py", line 224, in request
    raise ApiException(http_resp=r)
nipyapi.nifi.rest.ApiException: (500)
Reason: Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Sat, 20 Jul 2019 17:40:33 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'X-XSS-Protection': '1; mode=block', 'Content-Length': '87', 'Server': 'Jetty(9.4.11.v20180605)'})
HTTP response body: The request was rejected because the URL contained a potentially malicious String "%2F"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/nipyapi/versioning.py", line 798, in deploy_flow_version
    raise ValueError(e.body)
ValueError: The request was rejected because the URL contained a potentially malicious String "%2F"
>>> 
```
>>> 

### Urgency

Blocking me from publishing the flow. 

Let me know if there is any workaround.

**Comment by saggarsunil** [comment]
I used a wrong URL

**Comment by Gupta-Amrit** [comment]
> I used a wrong URL

@saggarsunil I am also getting the same error. I have crossed checked the URLs but can not find what is wrong. Could you please tell me where did u made mistake.
