### ISSUE TITLE
list_all_process_groups(root) breaks unexpectedly

### ISSUE THREAD

**Issue by automationfirst** [Chaffelson/nipyapi#147]
Nipyapi version: 0.13
NiFi version: nifi-1.8.0-RC3
NiFi-Registry version: NA
Python version: 3.7.4
Operating System: Windows 2008 Server

### Description
I'm seeing below error by running below code. The code was working fine but breaks unexpectedly. Is this behavior because of large number of process groups and processors. We large number of process groups deployed to replicate data.

The code was running fine for sometime and was able to get the dictionary of process groups deployed onto canvas but started breaking all of a sudden.

import nipyapi
import json

parent_group_id_dict = {}
query_db_table_dict = {}
parent_group_id_list = []

nipyapi.config.nifi_config.host = 'http://ip_address/nifi-api'
root = nipyapi.canvas.get_root_pg_id()
        
#Get a list of all ProcessGroups on the NiFi Canvas.
nifiRoot = nipyapi.canvas.get_process_group_status(pg_id='root', detail='names')
nifiCanvas = nifiRoot['NiFi Flow']
pgs = nipyapi.canvas.list_all_process_groups(pg_id = root)  
for pg in pgs:
    parentGroupID = pg.component.parent_group_id
    if (parentGroupID == nifiCanvas):
        id = pg.component.id
        pg_name = pg.component.name

        # Append the ProcessGroupGUID's to the list to be used to get the list of connections in a process group rather than going for the nested loop
        parent_group_id_dict[id]=pg_name
        parent_group_id_list.append(id)
print(parent_group_id_dict)

### What I Did

Error Message
-----------------
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 89, in get_flow
    return nipyapi.nifi.FlowApi().get_flow(pg_id)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\nifi\apis\flow_api.py", line 1865, in get_flow
    (data) = self.get_flow_with_http_info(id, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\nifi\apis\flow_api.py", line 1946, in get_flow_with_http_info
    collection_formats=collection_formats)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\nifi\api_client.py", line 326, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\nifi\api_client.py", line 153, in __call_api
    _request_timeout=_request_timeout)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\nifi\api_client.py", line 349, in request
    headers=headers)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\nifi\rest.py", line 233, in GET
    query_params=query_params)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\nifi\rest.py", line 224, in request
    raise ApiException(http_resp=r)
nipyapi.nifi.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Sat, 31 Aug 2019 06:25:44 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'Content-Type': 'application/json'
, 'Vary': 'Accept-Encoding', 'Content-Length': '40', 'Server': 'Jetty(9.4.11.v20180605)'})
HTTP response body: java.net.SocketTimeoutException: timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getProperties_nifi_new.py", line 33, in <module>
    pgs = nipyapi.canvas.list_all_process_groups(pg_id = root)  
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 185, in list_all_process_groups
    root_flow = recurse_flow(pg_id)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 70, in recurse_flow
    return _walk_flow(get_flow(pg_id))
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 66, in _walk_flow
    recurse_flow(pg.id)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 70, in recurse_flow
    return _walk_flow(get_flow(pg_id))
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 66, in _walk_flow
    recurse_flow(pg.id)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 70, in recurse_flow
    return _walk_flow(get_flow(pg_id))
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 66, in _walk_flow
    recurse_flow(pg.id)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 70, in recurse_flow
    return _walk_flow(get_flow(pg_id))
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 66, in _walk_flow
    recurse_flow(pg.id)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 70, in recurse_flow
    return _walk_flow(get_flow(pg_id))
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 66, in _walk_flow
    recurse_flow(pg.id)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 70, in recurse_flow
    return _walk_flow(get_flow(pg_id))
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nipyapi\canvas.py", line 91, in get_flow
    raise ValueError(err.body)
ValueError: java.net.SocketTimeoutException: timeout

### Urgency

It is somewhat urgent as it is blocking a production deployment

**Comment by Chaffelson** [comment]
Sounds like a timeout while the requests package is communicating with the NiFi REST endpoint. I will try to duplicate the timeout and see if we can expose a setting to manage it.

**Comment by automationfirst** [comment]
I have modified the logic to avoid using nipyapi.canvas.list_all_process_groups(pg_id = root) function.. Things appears to work fine..
