### ISSUE TITLE
nipyapi.security.list_service_users(service='registry') is unable to log in

### ISSUE THREAD

**Issue by jrittenh** [Chaffelson/nipyapi#187]
* Nipyapi version: master
* NiFi version: 1.11.3
* NiFi-Registry version: 0.5.0
* Python version: 3.7.4
* Operating System: macOS 10.14.6

### Description

While trying to retrieve a list of existing users from a registry, the api crashes.  It appears that the login context gets lost somewhere.

### What I Did

    nipyapi.security.service_login(**login_args)
    nipyapi.security.list_service_users(service='registry')

    Traceback (most recent call last):
      File "./initialize_nifi.py", line 546, in <module>
        nifi_users = nipyapi.security.list_service_users(service=target_service)
      File "/media/code/nipyapi/nipyapi/security.py", line 539, in list_service_users
        out = getattr(nipyapi, service).TenantsApi().get_users()
      File "/media/code/nipyapi/nipyapi/registry/apis/tenants_api.py", line 587, in get_users
        (data) = self.get_users_with_http_info(**kwargs)
      File "/media/code/nipyapi/nipyapi/registry/apis/tenants_api.py", line 661, in get_users_with_http_info
        collection_formats=collection_formats)
      File "/media/code/nipyapi/nipyapi/registry/api_client.py", line 326, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/media/code/nipyapi/nipyapi/registry/api_client.py", line 138, in __call_api
        self.update_params_for_auth(header_params, query_params, auth_settings)
      File "/media/code/nipyapi/nipyapi/registry/api_client.py", line 508, in update_params_for_auth
        auth_setting = config.auth_settings().get(auth)
      File "/media/code/nipyapi/nipyapi/registry/configuration.py", line 231, in auth_settings
        'value': self.get_basic_auth_token()
      File "/media/code/nipyapi/nipyapi/registry/configuration.py", line 202, in get_basic_auth_token
        return urllib3.util.make_headers(basic_auth=self.username + ':' + self.password)\
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### Urgency

low - I have worked around the issue with a direct API call.

**Comment by Chaffelson** [comment]
Could you please test this with 0.14.1 ? I thought I had tested yesterday's
minor security changes thoroughly but perhaps not

**Comment by jrittenh** [comment]
I was hitting this prior to yesterday, but failed to file a ticket immediately.  I did go ahead and test against a few versions and confirmed this goes back to at least 0.11.0.

**Comment by jrittenh** [comment]
I apologize.  This appears to work in v.0.13.0 and later.  After being very deliberate with pipenv targeting specific versions and refreshing the environment, I can fairly definitively say that.  I'm not sure what I was doing previously, but whatever it was, it wasn't properly refreshing the environment.

**Comment by Chaffelson** [comment]
Thanks for taking the time to validate and clear this up!
