### ISSUE TITLE
Cannot create empty groups

### ISSUE THREAD

**Issue by Amorik** [Chaffelson/nipyapi#194]
* Nipyapi version: 0.14.3
* NiFi version: 1.11.0
* NiFi-Registry version: N/A
* Python version: 3.6.8
* Operating System: Windows 10 Enterprise

### Description
Creating an empty group results in `TypeError: 'NoneType' object is not iterable`. Reviewing the function it's expected since the default values for argument `users` is `None`. However assigning users to a group is not a requirement for creation. Nipyapi should either make the argument mandatory or handle the exception.

### What I Did
```
nipyapi.security.create_service_user_group('groupname')
```

```
Traceback (most recent call last):
  File "/c/Users/matthew.gaetano/Documents/CGIMSS/GITLAB/MRU/cgimss-mru-edge/deploy.new.py", line 204, in <module>
    main()
  File "/c/Users/matthew.gaetano/Documents/CGIMSS/GITLAB/MRU/cgimss-mru-edge/deploy.new.py", line 171, in main
    deploy_nifi(nifi_ca=nifi_ca, nifi_cert=nifi_cert, nifi_key=nifi_key, nifi_key_password=nifi_password)
  File "/c/Users/matthew.gaetano/Documents/CGIMSS/GITLAB/MRU/cgimss-mru-edge/deploy.new.py", line 93, in deploy_nifi
    nipyapi.security.create_service_user_group('testgroup1')
  File "/c/Users/matthew.gaetano/Documents/CGIMSS/GITLAB/MRU/venv/lib/python3.6/site-packages/nipyapi/security.py", line 159, in create_service_user_group
    assert all(isinstance(user, nipyapi.nifi.UserEntity) for user in users)
TypeError: 'NoneType' object is not iterable
```

### Urgency

Non-urgent. Workaround is to set the argument `users` to an empty list:
```
nipyapi.security.create_service_user_group('groupname', users=[])
```

**Comment by razdob15** [comment]
@Chaffelson , are you working on this issue? Or can I create a PR for it?

**Comment by Chaffelson** [comment]
I've flagged it for the next release but not started on it yet, please go
right ahead :)
