### ISSUE TITLE
automated deployment with Nested PG and external controller services giving issues

### ISSUE THREAD

**Issue by charu123409** [Chaffelson/nipyapi#214]
* Nipyapi version: Latest
* NiFi version: 
1.11.4
* NiFi-Registry version:
* Python version: 3.7

### Description

I am trying to do deployment from one registry to another of my flow.
My flow contains nested PG and external controller services and parameter contexts and RPG.
when i run the deploy_version method of nipyapi, it gives below error

Traceback (most recent call last):
  File "C:\Program Files\Python\lib\site-packages\nipyapi\utils.py", line 520, in rest_exceptions
    yield
  File "C:\Program Files\Python\lib\site-packages\nipyapi\versioning.py", line 766, in deploy_flow_version
    version=target_flow.version
  File "C:\Program Files\Python\lib\site-packages\nipyapi\nifi\apis\process_groups_api.py", line 858, in create_process_group
    (data) = self.create_process_group_with_http_info(id, body, **kwargs)
  File "C:\Program Files\Python\lib\site-packages\nipyapi\nifi\apis\process_groups_api.py", line 945, in create_process_group_with_http_info
    collection_formats=collection_formats)
  File "C:\Program Files\Python\lib\site-packages\nipyapi\nifi\api_client.py", line 326, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "C:\Program Files\Python\lib\site-packages\nipyapi\nifi\api_client.py", line 153, in __call_api
    _request_timeout=_request_timeout)
  File "C:\Program Files\Python\lib\site-packages\nipyapi\nifi\api_client.py", line 371, in request
    body=body)
  File "C:\Program Files\Python\lib\site-packages\nipyapi\nifi\rest.py", line 268, in POST
    body=body)
  File "C:\Program Files\Python\lib\site-packages\nipyapi\nifi\rest.py", line 224, in request
    raise ApiException(http_resp=r)
nipyapi.nifi.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Sun, 09 Aug 2020 09:16:10 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'X-XSS-Protection': '1; mode=block', 'Strict-Transport-Security': 'max-age=31540000', 'Content-Type': 'text/plain', 'Vary': 'Accept-Encoding', 'Content-Length': '79', 'Server': 'Jetty(9.4.19.v20190610)'})
HTTP response body: An unexpected error has occurred. Please check the logs for additional details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/charu_chaudhary/Desktop/DataIng/Data_Pipeline/features/tests/automated_deployment -new - args.py", line 169, in <module>
    version=None
  File "C:\Program Files\Python\lib\site-packages\nipyapi\versioning.py", line 766, in deploy_flow_version
    version=target_flow.version
  File "C:\Program Files\Python\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Program Files\Python\lib\site-packages\nipyapi\utils.py", line 523, in rest_exceptions
    raise ValueError(e.body)
ValueError: An unexpected error has occurred. Please check the logs for additional details.

### What I Did

same as description.
I exported flow from registry 1
imported in bucket of registry2

    nipyapi.versioning.deploy_flow_version(
        parent_id=nipyapi.canvas.get_root_pg_id(),
        location=(0, 0),
        bucket_id=prod_bucket.identifier,
        flow_id=prod_flow.identifier,
        reg_client_id=reg_client.id,
        version=None
    )

### Urgency

It is blocking me to do deployment in production environment deployment, please help asap.
deployment is supposed to be next week.

Please help!!!!!

**Comment by Chaffelson** [comment]
Nested PGs generally aren't supported anyway, and don't work well in
registry.
The error you received says that you need to check the NiFi log as the
server was unable to process your submission, but what you are trying to do
probably won't work anyway.

**Comment by charu123409** [comment]
Thanks for your response, could you suggest how to handle this in that case? My parent PG has 4 PGs inside and processors.
Also one question does this automated deployment cater external controller services an parameter context??

**Comment by Chaffelson** [comment]
Controllers are imported if attached to the versioned PG. Parameter
contexts are not importable in that way, you must recreate them via the GUI
or API.
The standard design is a flat set of PGs that you connect together with
input/output ports

**Comment by charu123409** [comment]
One more doubt, it won't even work from one bucket to another within same registry?
then how do we do deployment in that case for nested PGs?
please respond

**Comment by Chaffelson** [comment]
Don't use nested PGs, or only version the top most one.

**Comment by charu123409** [comment]
I tried the second part wherein only top most is versioned but dint work.

I removed versioning for all the sub PGs and versioned the top most one but still faced the above issue. I am not sure whats happening.

**Comment by charu123409** [comment]
Could you please respond, its bit urgent at my end?

**Comment by Chaffelson** [comment]
Closing as old, please reopen if the issue persists
