### ISSUE TITLE
Not able to install on py 3.7

### ISSUE THREAD

**Issue by shrikant-pa** [Chaffelson/nipyapi#73]
* Python version: 3.7
* Operating System: Windows 10 Pro

### Description

I am not able to install nipyapi using pip. I check the pip list and it is showing latest packages. 

### What I Did
I ran pip install nipyapi and it gave me below error. 

Complete output from command python setup.py egg_info:
    Warning: 'keywords' should be a list, got type 'NoneType'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...\ruamel.yaml\setup.py", line 858, in <module>
        main()
      File "C:\Users\...\ruamel.yaml\setup.py", line 847, in main
        setup(**kw)
      File "c:\python\lib\site-packages\setuptools\__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "c:\python\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python\lib\site-packages\setuptools\dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "c:\python\lib\distutils\dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "c:\python\lib\distutils\dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "c:\python\lib\distutils\dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable

Command "python setup.py egg_info" failed with error code 1 in C:\Users\...\AppData\Local\Temp\pip-install-wjym60pp\ruamel.yaml\

**Comment by Chaffelson** [comment]
This is due to a dependency in Ruamel.Yaml, which requires that we upgrade to their 0.15 branch, which is an excellent idea and someone opened a PR for it.
It does however require some refactoring work to ensure that everything behaves correctly after the upgrade. I am hoping to have some time for that this week.
In the meantime, I suggest that an older version of Python would work.

**Comment by gaving** [comment]
Just chiming in to say I've been burned by this today, will use an older version of Python!
